language: c
script: echo 'hi, "$TRAVIS_BUILD_DOCS"'
after_success:
- |-
  if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
    echo 'made it inside if statement'
#    pwd
#    cd $PROJECT_DIR_ABS
    pwd
    source .ci/setup-ssh.sh || travis_terminate 1
    .ci/generateDocumentation.sh || travis_terminate 1
  fi

before_install:
- openssl aes-256-cbc -K $encrypted_bc2b37132209_key -iv $encrypted_bc2b37132209_iv
  -in .ci/travis_deploy_key.enc -out .ci/travis_deploy_key -d

