language: c

before_install:
- openssl aes-256-cbc -K $encrypted_bc2b37132209_key -iv $encrypted_bc2b37132209_iv
  -in .ci/travis_deploy_key.enc -out .ci/travis_deploy_key -d
- sudo apt-get install doxygen libopenmpi-dev
- test -n $CC && unset CC
- ls /usr/lib/openmpi/lib/
- which mpicc

script: 
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=~/local -DMPI_C_COMPILER=mpicc
- make install
- ctest
- cd ..
- mkdir build_examples
- cd build_examples
- cmake ../examples -DCMAKE_INSTALL_PREFIX=~/local
- make
- ./compress_1D
- cd ..
  

after_success:
- |-
  if [[ "$TRAVIS_BRANCH" = "master" && -n "$TRAVIS_BUILD_DOCS" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
    source .ci/setup-ssh.sh || travis_terminate 1
    source .ci/generateDocumentation.sh || travis_terminate 1
  fi
